function [fitresult, gof] = createFit(m)
%CREATEFIT(M)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: m
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Aug-2013 15:35:21


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], m );

% Set up fittype and options.
ft = fittype( 'poly2' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf -Inf];
opts.Robust = 'Bisquare';
opts.Upper = [Inf Inf Inf];
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'm', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% ylabel( 'm' );
% grid on


